### ISSUE TITLE
All the line breaks are removed from the subtitle

### ISSUE THREAD

**Issue by Essam3115** [subdiox/subs-dl#1]
Hi, in your userscript all the line breaks are removed from the downloaded subtitle file in SRT format using the latest version 1.0.2 on Firefox with Tampermonkey, and this happens even before converting the subtitle file to SRT when I used

https://github.com/subdiox/subs-dl/blob/277cf729965fff00b13a9adb8cbdc20299b3d3c6/hulu.user.js

please fix the script when you have the time, and one more thing, the script does not work all the time and I need to refresh the video's page to make it works, this problem fixed for me when I replaced

// @match        https://www.hulu.com/watch/*

with

// @match        https://www.hulu.com/*

the subtitle file in vtt format looks like this when I open it with notepad++ in Word wrap (the problem might be from Tampermonkey for Firefox)

<img width="909" alt="sub" src="https://user-images.githubusercontent.com/85903831/121956999-1b185280-cd62-11eb-92fe-9fa7c1957838.png">

**Comment by Essam3115** [comment]
The problem of the removed line breaks seems to happen only on Firefox, on Google Chrome the script downloads the subtitles in SRT format without any problems.

<img width="241" alt="sub2" src="https://user-images.githubusercontent.com/85903831/122027815-ba256480-cdcb-11eb-9613-cf5aa2881f6f.png">

**Comment by subdiox** [comment]
Thank you for your contribution. I'll update the script to make it work on Firefox too, so I re-open this issue.
